name: GitHub Actions Demo
env:
  FILENAME: hello-server
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
    - name: Build em Linux
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build em Windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    # - name: Upload artifact for linux
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
    #     name: linux
    #     path: ./${{ env.FILE_NAME }}

    # - name: Upload artifact for windows
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
    #     name: windows
    #     path: ./${{ env.FILE_NAME }}.exe