name: Go Hello-Server

env:
  FILE_NAME: hello-server

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * 1-6"
    
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5.0.2

      - name: Build Linux
        run: go build ${{env.FILE_NAME}}.go
  
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build ${{env.FILE_NAME}}.go
  
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v4.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
  
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v4.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
          
  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: Manage permissionsrun.sh
        run: chmod +x ./run.sh

      - name: Run Script
        run: ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
